In [2]:
import glob
import os.path as osp
import numpy as np
from skimage import transform as trans
from insightface import model_zoo

In [3]:
models = {}
onnx_files = glob.glob(osp.join("buffalo_l", '*.onnx'))
onnx_files = sorted(onnx_files)
for onnx_file in onnx_files:
    model = model_zoo.get_model(onnx_file)
    models[model.taskname] = model
    print(f"{onnx_file}: {model.taskname}")
models


/Users/ryoi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:65: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CoreMLExecutionProvider, CPUExecutionProvider'
  warnings.warn(


Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
buffalo_l/1k3d68.onnx: landmark_3d_68
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
buffalo_l/2d106det.onnx: landmark_2d_106
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
buffalo_l/det_10g.onnx: detection
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
buffalo_l/genderage.onnx: genderage
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
buffalo_l/w600k_r50.onnx: recognition


{'landmark_3d_68': <insightface.model_zoo.landmark.Landmark at 0x298276090>,
 'landmark_2d_106': <insightface.model_zoo.landmark.Landmark at 0x298a57e90>,
 'detection': <insightface.model_zoo.retinaface.RetinaFace at 0x298a56e10>,
 'genderage': <insightface.model_zoo.attribute.Attribute at 0x298a62e50>,
 'recognition': <insightface.model_zoo.arcface_onnx.ArcFaceONNX at 0x298a63550>}

In [4]:
models['recognition'].input_std, models['recognition'].input_mean

(127.5, 127.5)

In [31]:
face_analyzer.models['recognition'].input_size

(112, 112)

In [22]:
import insightface
import cv2

face_analyzer = insightface.app.FaceAnalysis(name='buffalo_l')
face_analyzer.prepare(ctx_id=0, det_size=(640, 640))

source_face = face_analyzer.get(cv2.imread("suzu.jpg"))
source_face[0].kps

/Users/ryoi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:65: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CoreMLExecutionProvider, CPUExecutionProvider'
  warnings.warn(


Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ryoi/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ryoi/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ryoi/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ryoi/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ryoi/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det

/Users/ryoi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


array([[202.74226, 244.4472 ],
       [313.3518 , 236.377  ],
       [268.47104, 308.41437],
       [210.28708, 345.52072],
       [317.69244, 337.33417]], dtype=float32)

In [51]:
target_face = face_analyzer.get(cv2.imread("org.jpg"))
target_face[0].kps

/Users/ryoi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


array([[124.10656, 128.83286],
       [168.6889 , 136.93382],
       [150.91977, 158.33789],
       [123.58283, 181.42784],
       [155.79482, 187.98782]], dtype=float32)

In [52]:
target_face

[{'bbox': array([ 79.132126,  68.74858 , 185.10017 , 213.50414 ], dtype=float32),
  'kps': array([[124.10656, 128.83286],
         [168.6889 , 136.93382],
         [150.91977, 158.33789],
         [123.58283, 181.42784],
         [155.79482, 187.98782]], dtype=float32),
  'det_score': 0.85901725,
  'landmark_3d_68': array([[ 7.39025040e+01,  1.25185280e+02,  4.92487221e+01],
         [ 7.43106232e+01,  1.40727692e+02,  4.74828758e+01],
         [ 7.55823669e+01,  1.56366135e+02,  4.47886581e+01],
         [ 7.76536636e+01,  1.71035492e+02,  4.05723190e+01],
         [ 8.33653259e+01,  1.84670639e+02,  3.14300842e+01],
         [ 9.20498352e+01,  1.95127106e+02,  2.36526203e+01],
         [ 1.03473305e+02,  2.02999069e+02,  1.80794029e+01],
         [ 1.17906631e+02,  2.09287720e+02,  1.07016783e+01],
         [ 1.34425781e+02,  2.16130707e+02,  1.19322395e+01],
         [ 1.46763687e+02,  2.14000443e+02,  2.46091022e+01],
         [ 1.54284683e+02,  2.10020309e+02,  4.09448433e+01],
  

In [61]:
target_face[0].kps

array([[124.10656, 128.83286],
       [168.6889 , 136.93382],
       [150.91977, 158.33789],
       [123.58283, 181.42784],
       [155.79482, 187.98782]], dtype=float32)

In [74]:
face_analyzer.models['recognition'].get(cv2.imread("org.jpg"), target_face[0])
target_face[0].normed_embedding[200]

0.01782848

: 

In [ ]:
norm_crop(cv2.imread("org.jpg"), landmark=target_kps, image_size=arcface.input_size[0])